### ISSUE TITLE
Improve evalcov for dense matrices

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/gvar#12]
Even after the 11.4 update, evalcov_blocks is still the bottleneck of my scripts. I've seen the new implementation uses evalcov, and spends around 50 % of the time in it for the dense case:

```python
import numpy as np
import gvar
n = 100
a, b = np.random.randn(2, n, n)
cov = a.T @ a
x = b @ gvar.gvar(np.zeros(n), cov)
%timeit gvar.evalcov_blocks(x)
%timeit gvar.evalcov(x)
```

Output:

```
34.4 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
17.9 ms ± 509 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

I figured that for the dense case first converting everything to dense matrices and then multiplying would give an improvement, so I made this test:

```python
from scipy import sparse
b_sparse = sparse.csr_matrix(b)
cov_sparse = sparse.csr_matrix(cov)
def evalcov_dense_mockup():
    b_dense = b_sparse.toarray() # emulate converting gvars coeffs to a matrix
    cov_dense = cov_sparse.toarray()
    b @ cov @ b.T
%timeit evalcov_dense_mockup()
%timeit gvar.evalcov(x)
```

Output:

```
961 µs ± 45.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
17.9 ms ± 362 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

I've read the evalcov code and sketched a new algorithm. If you allow, I'll try to implement this and make a pull request.

  * Build the mask as usual reading the indices from `d` attributes, while also
    counting the total number of elements.
  
  * Get the count of primary gvars involved by summing the mask.
  
  * Count the number of nonzero entries in `cov` with the mask. Probably
    requires a new `smat` method.
    
  * Using the counts and the number of primary gvars, determine if the dense
    algorithm would be convenient; if it isn't, proceed as usual. Up to here the only overhead is counting nonzeros in cov.
    
  * Extract a dense submatrix from `cov` using the mask. Probably requires a
    new `smat` method, and probably it is convenient to first convert the
    mask to a mapping, i.e. replace the 1s with the cumsum of the 1s, they then
    point to the destination index with an offset of +1.
    
  * Write `d` elements into a dense matrix, using the mapping as above.
    Probably requires a new `svec` method, which could be used by the `smat`
    method above.
    
  * Perform the matrix multiplication.
  
  * Optionally, as a further optimization, copy only a triangular part of
    `cov` halving diagonal elements, use `BLAS_xtrmm` for doing the matrix
    multiplication, and finally take twice the symmetrical part of the result.

**Comment by gplepage** [comment]
Sounds like it is worth a try. I'll merge it into the code if makes a big enough difference and if I think I can maintain it. Your sketch looks good to me. In particular, it is good to build it on top of new methods in svec and smat -- I expect someday to replace svec and smat, so it is helpful to keep their implementation details out of other code.

I need to fix some remaining problems in evalcov_blocks with a new version, which I will probably release tomorrow. So you might want to wait for it before you start.

**Comment by gplepage** [comment]
I can make a simple version of this pretty quickly. I will add an experimental evolcov_expt to the next release (out in a day or two) to allow for some experimentation.

**Comment by Gattocrucco** [comment]
Good, I'll wait for the next release then.

**Comment by gplepage** [comment]
I built an implementation of your optimization into the new release (up in a few minutes). It makes a big difference for big matrices (1000x1000), but is slower for smaller matrices (less than 200x200).

**Comment by gplepage** [comment]
This now works well for covariance matrices larger than 15x15 and much better for very large matrices (v11.5.2).
