### ISSUE TITLE
Missing signature in docstrings for cython-compiled functions

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/gvar#13]
Example:

```python
import gvar
help(gvar.evalcov_blocks)
```

Output:

```
evalcov_blocks(...)
    Evaluate covariance matrix for elements of ``g``.
    
    Evaluates the covariance matrices for |GVar|\s stored in
    array or dictionary of arrays/|GVar|\s ``g``. The covariance matrix is
[...]
```

If I remember correctly, in numpy this is solved by copy-pasting the signature in the docstring for all compiled functions. May I do this and make a pull request? It should be quick.

**Comment by gplepage** [comment]
There is a better way to do this. It will be in the next version (which will be up soon).

**Comment by gplepage** [comment]
Any quick way of doing this messes up the online documentation. I will fix it in the release after the next one.

**Comment by Gattocrucco** [comment]
Thanks, no hurry.

**Comment by gplepage** [comment]
This should be working now (v11.5.2).

**Comment by Gattocrucco** [comment]
It does, closing the issue.
