### ISSUE TITLE
var(None) segfaults

### ISSUE THREAD

**Issue by dchackett** [gplepage/gvar#14]
To reproduce failure:
```
import gvar as gv
gv.var(None)
# also: gv.var([None])
```
This segfaults and kills the kernel (tested in both macOS and Ubuntu). Issue present with gvar 11.8, numpy 1.19.4, Python 3.7.6, Cython 0.29.21; seems to be new in gvar 11.8 vs gvar 11.7.

**Comment by gplepage** [comment]
A fix will be included in the next release, sometime next week.

**Comment by gplepage** [comment]
Version 11.9 fixes this problem in ``gvar.var`` and several other functions. Thanks for pointing it out.

**Comment by gplepage** [comment]
Closing this issue because it has been dealt with (version >= 11.9).
