### ISSUE TITLE
Zero division in evalcov

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/gvar#15]
I'm dumping a dictionary with `gvar.dump`. The dictionary contains many `gvar`s and `lsqfit.nonlinear_fit`s. I have the latest version of `gvar` and `lsqfit` installed. The script fails with this traceback:

```
_utilities.pyx in gvar._utilities.dump()

_utilities.pyx in gvar._utilities.gdumps()

_utilities.pyx in gvar._utilities.gdump()

_utilities.pyx in gvar._utilities._gdump()

_utilities.pyx in gvar._utilities.evalcov_blocks()

_utilities.pyx in gvar._utilities.evalcov()

ZeroDivisionError: float division
```

I looked at the code of `evalcov`, the only division I see is at line 987 `is_dense = cov_zeros / ni / ni < 0.5`, although I would not expect `ni` to be zero. I've not used `gvar.switch_gvar()` or done other messes.

I can share the code if needed but it's long. I'm sorry I can not provide a minimal working example right now.

**Comment by gplepage** [comment]
Can you replace line 987 with ``is_dense = (cov_zeros/ni/ni < 0.5) if ni > 0 else True``and rerun your example to see if the problem goes away? That would at least prove that the problem is in that line.

**Comment by Gattocrucco** [comment]
Test done. I confirm that replacing line 987 fixes everything.

**Comment by gplepage** [comment]
Thanks for checking. 

I have figured out how this can happen and how to fix it. Line 987 can be replaced by ``is_dense = (cov_zeros/ni/ni < 0.5) if ni > 0 else False``  -- note ``False`` not ``True`` unlike what I suggested above. 

I will put a slightly better solution into the code, which will be up shortly.

**Comment by gplepage** [comment]
Version 11.9.2 (just up) should fix this issue.

**Comment by Gattocrucco** [comment]
It works, thanks for the very quick release.
