### ISSUE TITLE
Feature request: new primary gvars correlated with preexisting primary gvars

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/gvar#22]
I wanted to implement Bayesian optimization using `gvar`. In Bayesian optimization you cycle between using the fit to decide where to get the next datapoint, and redoing the fit with the new datapoint.

The fit is a Gaussian process inference which I want to do with `gvar`, which implies creating correlated primary gvars representing the Gaussian process prior. This means that every time I add a point, it must be correlated with previous points. However, I don't know in advance all the points, so I can't compute the covariance matrix before creating the first set of gvars. Thus I would need an interface to create new gvars correlated to preexisting primary gvars.

I see that in the implementation of `smat` there is an incremental block index associated to each new set of correlated primary gvars. Adding new gvars correlated with old ones would be a problem because either the monotonicity of the block index or the independence of extraneous gvars created between the old and new ones would be lost. Anyway, I think the latter case would not be a serious problem in practice. What to do depends on the assumptions on the block index you used in implementing `evalcov_blocks`.

I'd propose an interface like this:

```python
x = gvar.gvar(xmean, xcov)
y = gvar.gvar(ymean, ycov, x, xycov)
# xycov is a len(x)*len(y) matrix (or equivalent tensor or bufferdict)
# raises an exception if x contains non-primary gvars
```

Alternative:

```python
x = gvar.gvar(xmean, xcov)
y = gvar.gvar(ymean, ycov)
gvar.addcov(x, y, xycov)
# raises an exception if x or y contain non-primary gvars
```

I prefer the first interface because in the second it would be possible to compute stuff with `y` and then change the results post-facto by introducing other correlations, while in the first the correlations can be added only at the creation of `y`, maintaining coherence.

This kind of interface is very user-friendly but requires a bit of effort to implement to keep into account that the gvars in `x` can appear in any order from any block. A simpler internal-only thing, that would be fine for my needs, could be a function to add off-diagonal covariance blocks aligned with already defined blocks:

```python
x = gvar.gvar(xmean, xcov)
y = gvar.gvar(ymean, ycov)
def blockid(g):
    assert g.is_primary()
    return g.internaldata[2].blockid(g.internaldata[1].indices()[0])
gvar._addcovblock(blockid(x[0]), blockid(y[0]), xycov)
# I guess _addcovblock would set the block id of y to the one of x
```

Can you do something like this?

If you don't have time, I can try to code something myself and make a pull request (always following your choices on the details of course).

**Comment by gplepage** [comment]
I am very reluctant to do this. ``GVar``s are currently immutable and I have relied on that in various design decisions over time. That would no longer be the case with this change.

It would also be quite messy to implement for the reason you indicate and might lead to a performance hit.

I frequently use ``GVar``s for Bayesian iterations of the sort you describe. Typically your ``y`` would be some function of ``x`` and so would be appropriately correlated. It would not be a primary ``GVar``, however, although one could, after the fact, redefine ``x`` and ``y`` to both be primary. In my applications it makes no difference whether ``y`` is primary or not.

**Comment by Gattocrucco** [comment]
Ok. I'll try to convince you that this modification is important to me and that it won't break something.

> GVars are currently immutable and I have relied on that in various design decisions over time.

If you allow the user to define new correlations *only with new* gvars, at their creation, then it is mathematically impossible that previous gvars, primary or not, change correlation/variance. And the individual gvar objects do not change. Changing the blockids matters only to `evalcov_blocks`, and they are not referenced in other places other than in the global `smat`, so changing them in a coherent way won't break anything.

> and might lead to a performance hit.

It would lead to a performance hit only insofar as there are more correlations, I think, as it would happen anyway if I was able to define all primary gvars at once.

> In my applications it makes no difference whether y is primary or not.

In my application (Gaussian processes), the covariances are defined by a kernel which is, let's say, God-given, so I have a function which I use to compute all the covariances, and the variables are full-rank, so as I add variables I can not write them as a transformation of old ones. I could write them as a transformation of old ones *and* new independent gvars, but this would require computing the appropriate transformation from the covariance matrix blocks, which requires to decompose the *full* covariance matrix of previous gvars. This would be inefficient if not altogether unfeasible, and it would also bring about numerical accuracy problems since these matrices are often badly conditioned.

(The formula is the following: let `x` be the old variables, `y` the new ones, and `z` auxiliary new variables. The desired covariance matrix is

```
V = | V_xx   V_xy |
    | V_yx   V_yy |
```

And I want to write `y` as

```
y = Az + Bx
```

So, computing the covariance blocks:

```
Cov[x, y] = Cov[x, Bx] = V_xx B^T = V_xy   ==>  B^T = V_xx^-1 V_xy
Cov[y, y] = Cov[Az, Az] + Cov[Bx, Bx] = A V_zz A^T + B V_xx B_T = V_yy  ==>
    ==>  A V_zz A^T = V_yy - V_yx V_xx^-1 V_xy = V/V_xx (Schur's complement)
```

I can choose `A = I` so then `V_zz = V/V_xx`. I have to decompose `V_xx`.)

I could implement this functionality in a fork and maintain it, but it would be incovenient because I am writing a module and not just a standalone program: it would be a mess for the user experience to have to install two competing versions of gvar, and my module works in concert with lsqfit, so I would probably also need to fork lsqfit.

So I reiterate my proposal: I can try to implement this, respecting any implementation detail that matters for your future plans, make all tests necessary to ensure that nothing is going awry, and then make a pull request. If then you think it is fine when you see it working, you can decide if you want to accept the pull request.

I hope that I am not bothering you too much. I want to assure you that I care about gvar, I'm seriously invested in writing my module ([lsqfitgp](https://github.com/Gattocrucco/lsqfitgp)), which already by its name shows that I took inspiration from how you designed lsqfit. I will spend the next 2.5 years studying Gaussian process and improving lsqfitgp (I have funding), so I won't "run away" after requiring you to add features to gvar, you can always count on me to solve any problem which is my fault if it really comes to that.

To conclude, please consider again my feature request. I think it would make gvar more complete.

**Comment by gplepage** [comment]
I agree that this might not be so difficult to implement. I will look into it next week.

**Comment by Gattocrucco** [comment]
Thank you!!

**Comment by gplepage** [comment]
Still working on this.

**Comment by gplepage** [comment]
v11.10 implements your favored interface: ``gvar(ymean, ycov, x, xycov)``.

**Comment by Gattocrucco** [comment]
Thank you. And it works even if I change the order of `x`! It's full optional.
