### ISSUE TITLE
*.c files shipped in PyPI is not compatible with Python 3.11

### ISSUE THREAD

**Issue by SaltyChiang** [gplepage/gvar#32]
For the newest Python release 3.11, `pip install gvar` will raise `No such file or directory` error because some headers are in other folders now.
Maybe there should be *.c files for both versions, or automatically enable Cython to build if 3.11 is detected.

**Comment by gplepage** [comment]
Thanks for pointing this out -- I haven't tried Python 3.11 yet. 

Have you checked that rebuilding the *.c with Cython works? The setup.py file can be reconfigured to rebuild *.c files by setting parameter ``USE_CYTHON = True`` (it is set to ``False`` in the release).

I will experiment with 3.11 to see how to fix things and issue a new release. The easiest fix is to have setup.py set ``USE_CYTHON`` to ``True`` for 3.11, as you suggest.

**Comment by SaltyChiang** [comment]
> Have you checked that rebuilding the *.c with Cython works? The setup.py file can be reconfigured to rebuild *.c files by setting parameter `USE_CYTHON = True` (it is set to `False` in the release).

Yes. I change the flag to True and the compilation raises no error.

**Comment by gplepage** [comment]
Good! Thanks.

**Comment by SaltyChiang** [comment]
Thank you for the fix.
