### ISSUE TITLE
Feature request: clear history of `GVarFactory` objects

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/gvar#37]
I'm writing a script that repeats the same fit hundredths of times. Each time it generates about 1000 correlated primary gvars, so the memory usage is substantial. Moreover, I'd like to be able to repeatedly run the script in the same shell, as I usually do in development.

I thought about using `switch_gvar` at the beginning of the loop, but I discovered it keeps a full history of previous `GVarFactory`s, so the memory grows even if I dispose of all the gvars.

Could you add an option to not keep a full history? Something like `switch_gvar(keep_history=False)`, or a new function `clear_gvar()`. Currently, I do `gvar._GVAR_LIST.clear()`.

Example script showing the memory usage:

```python
import tracemalloc

import gvar
import numpy as np

n = 1000
r = 10
a = np.random.randn(n, n)
cov = a @ a.T
mean = np.random.randn(n)

class TraceMalloc:

    def __enter__(self):
        tracemalloc.start()

    def __exit__(self, *_):
        tracemalloc.stop()
        tracemalloc.clear_traces()

with TraceMalloc():

    initial_memory, _ = tracemalloc.get_traced_memory()

    for _ in range(r):

        gvar.switch_gvar()
        gvar.gvar(mean, cov)

        current_memory, _ = tracemalloc.get_traced_memory()
        memory = current_memory - initial_memory
        print(f'memory = {memory / 1e6:.0f} MB')

with TraceMalloc():

    initial_memory, _ = tracemalloc.get_traced_memory()

    print('\nWITH CLEARING:')
    for _ in range(r):

        gvar.switch_gvar()
        gvar._GVAR_LIST.clear()
        gvar.gvar(mean, cov)

        current_memory, _ = tracemalloc.get_traced_memory()
        memory = current_memory - initial_memory
        print(f'memory = {memory / 1e6:.0f} MB')
```

```
memory = 16 MB
memory = 32 MB
memory = 48 MB
memory = 64 MB
memory = 80 MB
memory = 96 MB
memory = 113 MB
memory = 129 MB
memory = 145 MB
memory = 161 MB

WITH CLEARING:
memory = 16 MB
memory = 16 MB
memory = 16 MB
memory = 16 MB
memory = 16 MB
memory = 16 MB
memory = 16 MB
memory = 16 MB
memory = 16 MB
memory = 16 MB
```

gvar version: 11.11.10

**Comment by gplepage** [comment]
There are two things you can do, either of which makes the first loop behave like the second one. First you can add ``gvar.restore_gvar()`` at the end of the first loop. Alternatively you can replace the ``gvar.switch_gvar()`` at the beginning of the first loop with ``gvar.gvar = gvar.gvar_factory()``:
```python
    for _ in range(r):

        # gvar.switch_gvar()
        gvar.gvar = gvar.gvar_factory()
        gvar.gvar(mean, cov)

        current_memory, _ = tracemalloc.get_traced_memory()
        memory = current_memory - initial_memory
        print(f'memory = {memory / 1e6:.0f} MB')
        # gvar.restore_gvar()
```  
Either modification keeps the memory at 16 MB.

**Comment by Gattocrucco** [comment]
Thanks, I had not thought about those tricks! I'll close the issue then.
