### ISSUE TITLE
Install gvar on the code interpreter

### ISSUE THREAD

**Issue by Greyyy-HJC** [gplepage/gvar#40]
Hi, did anyone tried to use gvar package in ChatGPT's code interpreter? How to make it? I found the answer to use external package in ChatGPT's code interpreter related to wheel file, but it seems no wheel file on PyPI for gvar...

**Comment by gplepage** [comment]
I am looking into the possibility of providing wheels but it will take a while.

**Comment by gplepage** [comment]
``gvar`` version 11.11.17 has wheel files on PyPi for recent versions of Python and some standard hardware options. I will do the same for ``lsqfit`` soon.

**Comment by Greyyy-HJC** [comment]
Wow, I'm shocked by how quickly you've responded and addressed the issue! Thank you so much and looking forward to the update on lsqfit.

**Comment by gplepage** [comment]
``lsqfit`` version 13.0.3 now comes in wheels as well.

**Comment by gplepage** [comment]
I am closing this issue now that wheels are available to lsqfit and gvar.
