### ISSUE TITLE
gvar.pxd is installed in toplevel

### ISSUE THREAD

**Issue by APN-Pucky** [gplepage/gvar#44]
I've been trying to add gvar (and vegas) to gentoo, but this error keeps poping up:
```
 * The following unexpected files/directories were found top-level
 * in the site-packages directory:
 * 
 *   /usr/lib/python3.11/site-packages/gvar.pxd
 * 
 * This is most likely a bug in the build system.  More information
 * can be found in the Python Guide:
 * https://projects.gentoo.org/python/guide/qawarn.html#stray-top-level-files-in-site-packages
 * ERROR: sci-libs/gvar-12.1::hep-forge failed (install phase):
```

I think it is related to https://github.com/gplepage/gvar/blob/e57768570d2deb087234c6bf5f09fd53568faf59/setup.cfg#L26
Could you maybe reconsider the package structure/build system there?

**Comment by gplepage** [comment]
Thanks for pointing out the problem. It used to be necessary to have pxd files at the top level but there is now a much better option. I think it will fix your problem. I should have a new version installed tomorrow.

**Comment by gplepage** [comment]
Version 13.0.2, which I just uploaded, should solve the problem.

**Comment by APN-Pucky** [comment]
Thanks, all seems to work now :), but the first example I could find in docs is (now) a little bit wrong commented, while the content of `__init__.py` is correct:
![2024-03-08_18-15-17_gvar](https://github.com/gplepage/gvar/assets/4533248/c8418aef-50f9-4284-a088-0c7285bade2d)
 https://gvar.readthedocs.io/en/latest/gvar.html
 
 Maybe some html file is cached/stored in the repo? Just wanted to let you know about that too.

**Comment by gplepage** [comment]
Thanks for that as well.
