### ISSUE TITLE
incompatible pointers

### ISSUE THREAD

**Issue by APN-Pucky** [gplepage/gvar#45]
![2024-03-16_10-45-07_apn](https://github.com/gplepage/gvar/assets/4533248/5f389199-4dba-4dc2-9ff9-fd42e7f25b85)

I am not sure about the implications of this QA warning for your package.

**Comment by gplepage** [comment]
It looks like a `cython` issue. Appears on my mac as well but doesn't seem to cause problems. I will play with it some more to see if I can get the warning to go away.

**Comment by gplepage** [comment]
I seem to be able to make this warning go away. It does appear to be a defect in `cython`, but it doesn't matter here -- the code functions properly despite the warning.

**Comment by APN-Pucky** [comment]
Thanks for looking into it
