### ISSUE TITLE
gvar 13.1 seems incompatible with numpy 2.0.0

### ISSUE THREAD

**Issue by AncelChow** [gplepage/gvar#46]
the latest version of numpy 2.0.0 has modified its C header, which causes an error while importing gvar. Here is the log:

```log
>>> import gvar as gv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ac/.venv/lib/python3.12/site-packages/gvar/__init__.py", line 127, in <module>
    from ._gvarcore import sin, cos, tan, exp, log, sqrt, fabs, sinh, cosh, tanh
  File "src/gvar/_gvarcore.pyx", line 1, in init gvar._gvarcore
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

version info:

gvar 13.1
numpy 2.0.0

**Comment by SaltyChiang** [comment]
It seems that the wheel files provided on PyPI are built with `numpy<2`, and installing `gvar` from the source solves the import issue. But `gvar` uses some removed API in `numpy=2.0.0`, these should be migrated to the new version.

```
$ python
Python 3.9.6 (default, Feb  3 2024, 15:58:27)
[Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gvar as gv
>>> import numpy as np
>>> np.__version__
'2.0.0'
>>> a = gv.gvar(12, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/gvar/_gvarcore.pyx", line 1319, in gvar._gvarcore.GVarFactory.__call__
  File "/Users/jxyzj/.venv/lib/python3.9/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.
>>>
```

**Comment by SaltyChiang** [comment]
Simply changing `numpy.float_` to `numpy.float64` as advised by NumPy works fine. All tests pass except for some assertions about converting objects containing `numpy.float64` to string. As described in https://numpy.org/devdocs/release/2.0.0-notes.html#representation-of-numpy-scalars-changed, setting `numpy.set_printoptions(legacy="1.25")` before those assertions should be a workaround for this.

**Comment by gplepage** [comment]
Thanks for reporting this and for finding a fix. I will fix the problem and post a new version, but it is unlikely to happen before next week.

**Comment by gplepage** [comment]
I just uploaded version 13.1.1. This should work with `numpy` 2.0.

**Comment by AncelChow** [comment]
> I just uploaded version 13.1.1. This should work with `numpy` 2.0.

Thanks a lot! It's working perfectly now.
I'll go ahead and close this issue. Really appreciate your help!

**Comment by AncelChow** [comment]
Sorry to reopen this, but it looks like the lsqfit package is having the same issue.

**Comment by gplepage** [comment]
Yes `lsqfit` has the same problem as does `vegas`. Both of them will be fixed today.

**Comment by AncelChow** [comment]
All lsqfit-related issues are now resolved. Thanks for your swift assistance! Closing this issue.
