### ISSUE TITLE
gvar_function does not work with non-scalars

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/gvar#7]
```python
import gvar
import numpy as np
gvar.gvar_function(gvar.gvar(np.arange(2), np.ones(2)),np.arange(2),np.zeros(2))
```

Error:

```
TypeError: only size-1 arrays can be converted to Python scalars
```

**Comment by gplepage** [comment]
According to the documentation, the second argument of ``gvar.gvar_function`` is supposed to be a float not an array (as in your example). So this is not a bug, but rather a feature request. 

The Python source code for the ``gvar.erf(x)`` in ``gvar.__init__.py`` shows one way to construct a function that can return an array of ``GVar``s using ``gvar.gvar_function``.

**Comment by Gattocrucco** [comment]
Sorry, I missed that: so it means I can just do something like f + gvar_function(x, 0, dfdx)
